### ISSUE TITLE
[Request] Provide GPS coordinates in location requests

### ISSUE THREAD

**Issue by Phil5555** [c3nav/c3nav#49] opened 2019-12-29 18:36 UTC
Please provide an API that maps c3nav coordinates mapped to GPS lat/lon.
So it is possible to to use more precises c3nav locations while in range and fall back to GPS while out of congress range/unknown c3nav locations

**Comment by codingcatgirl** [comment] 2019-12-29 19:44
duplicate of #52

**Closed by codingcatgirl** 2019-12-29 19:44 UTC
